In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.4.6 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/yanhaixiong/anaconda3/lib/python3.11/site-packages/ipykernel_launcher.py", line 17, in <module>
    app.launch_new_instance()
  File "/Users/yanhaixiong/anaconda3/lib/python3.11/site-packages/traitlets/config/application.py", line 992, in launch_instance
    app.start()
  File "/Users/yanhaixiong/anaconda3/lib/python3.11/site-packages/ipykernel/kernelapp.py", line 711, in start
    self.io_loop.start()
  

AttributeError: _ARRAY_API not found


A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.4.6 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/yanhaixiong/anaconda3/lib/python3.11/site-packages/ipykernel_launcher.py", line 17, in <module>
    app.launch_new_instance()
  File "/Users/yanhaixiong/anaconda3/lib/python3.11/site-packages/traitlets/config/application.py", line 992, in launch_instance
    app.start()
  File "/Users/yanhaixiong/anaconda3/lib/python3.11/site-packages/ipykernel/kernelapp.py", line 711, in start
    self.io_loop.start()
  

AttributeError: _ARRAY_API not found


A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.4.6 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/yanhaixiong/anaconda3/lib/python3.11/site-packages/ipykernel_launcher.py", line 17, in <module>
    app.launch_new_instance()
  File "/Users/yanhaixiong/anaconda3/lib/python3.11/site-packages/traitlets/config/application.py", line 992, in launch_instance
    app.start()
  File "/Users/yanhaixiong/anaconda3/lib/python3.11/site-packages/ipykernel/kernelapp.py", line 711, in start
    self.io_loop.start()
  

AttributeError: _ARRAY_API not found

In [2]:
# get some real data to play with for gradient descent
data = pd.read_csv('https://github.com/yanhai-xiong/DATA301-AML/blob/main/Data%20Sets/Advertising.csv?raw=true')

In [3]:
data

,Unnamed: 0,TV,Radio,Newspaper,Sales
0,1,230.1,37.8,69.2,22.1
1,2,44.5,39.3,45.1,10.4
2,3,17.2,45.9,69.3,9.3
3,4,151.5,41.3,58.5,18.5
4,5,180.8,10.8,58.4,12.9
...,...,...,...,...,...
195,196,38.2,3.7,13.8,7.6
196,197,94.2,4.9,8.1,9.7
197,198,177.0,9.3,6.4,12.8
198,199,283.6,42.0,66.2,25.5


## The Main Goals

We want to predict the Sales by using the feature values of TV, Radio and Newspaper advertising. We think of a weighted combination of TV, Radio and Newspaper amounts from commercials.

In [4]:
def MSE(w,x,y):
  return np.mean((y-x@w)**2) # here we use the "At" sign to represent the linear combiantion of columns in x by using the weights in w


In [5]:
# we use all the data as train data
x = data.loc[:,['TV','Radio','Newspaper']].values
y = data['Sales'].values

In [6]:
# here the input features are a Numpy array
x

array([[230.1,  37.8,  69.2],
       [ 44.5,  39.3,  45.1],
       [ 17.2,  45.9,  69.3],
       [151.5,  41.3,  58.5],
       [180.8,  10.8,  58.4],
       [  8.7,  48.9,  75. ],
       [ 57.5,  32.8,  23.5],
       [120.2,  19.6,  11.6],
       [  8.6,   2.1,   1. ],
       [199.8,   2.6,  21.2],
       [ 66.1,   5.8,  24.2],
       [214.7,  24. ,   4. ],
       [ 23.8,  35.1,  65.9],
       [ 97.5,   7.6,   7.2],
       [204.1,  32.9,  46. ],
       [195.4,  47.7,  52.9],
       [ 67.8,  36.6, 114. ],
       [281.4,  39.6,  55.8],
       [ 69.2,  20.5,  18.3],
       [147.3,  23.9,  19.1],
       [218.4,  27.7,  53.4],
       [237.4,   5.1,  23.5],
       [ 13.2,  15.9,  49.6],
       [228.3,  16.9,  26.2],
       [ 62.3,  12.6,  18.3],
       [262.9,   3.5,  19.5],
       [142.9,  29.3,  12.6],
       [240.1,  16.7,  22.9],
       [248.8,  27.1,  22.9],
       [ 70.6,  16. ,  40.8],
       [292.9,  28.3,  43.2],
       [112.9,  17.4,  38.6],
       [ 97.2,   1.5,  30. ],
       [26

In [7]:
# say pick a random set of weights
w = [1,2,3]

In [8]:
MSE(w,x,y)

np.float64(87288.4676)

We want to apply gradient descent to minimize the MSE. This means we need to differentiate MSE as a function of the weights.
A good idea is to standardize x and include a bias term OR center the values of y.

In [9]:
# you can center y but this may not be ideal in real situations
# an alternative would be to have a bias term w0 in the vector of the weights
y_centered = y - np.mean(y)

In [10]:
def zscore(x):
  return (x-np.mean(x))/np.std(x)

In [11]:
x_scaled = zscore(x)

In [12]:
# we need to include a column of 1s in x_scaled to accommodate the bias term
x_aug = np.column_stack([np.ones(len(x)),x_scaled])

In [13]:
x_aug

array([[ 1.00000000e+00,  2.12559023e+00, -3.79832818e-01,
         2.92690218e-02],
       [ 1.00000000e+00, -2.92540387e-01, -3.60289737e-01,
        -2.84723155e-01],
       [ 1.00000000e+00, -6.48224471e-01, -2.74300178e-01,
         3.05718939e-02],
       [ 1.00000000e+00,  1.10153276e+00, -3.34232295e-01,
        -1.10138293e-01],
       [ 1.00000000e+00,  1.48327429e+00, -7.31608286e-01,
        -1.11441165e-01],
       [ 1.00000000e+00, -7.58968600e-01, -2.35214015e-01,
         1.04835604e-01],
       [ 1.00000000e+00, -1.23167014e-01, -4.44976423e-01,
        -5.66143529e-01],
       [ 1.00000000e+00,  6.93733794e-01, -6.16955541e-01,
        -7.21185309e-01],
       [ 1.00000000e+00, -7.60271472e-01, -8.44958158e-01,
        -8.59289751e-01],
       [ 1.00000000e+00,  1.73081999e+00, -8.38443798e-01,
        -5.96109587e-01],
       [ 1.00000000e+00, -1.11200134e-02, -7.96751891e-01,
        -5.57023424e-01],
       [ 1.00000000e+00,  1.92494793e+00, -5.59629168e-01,
      

In [14]:
# we need the gradient of the objective function
def gradient(w,x,y):
  error = y - x@w
  n = len(y)
  return 2/n*error@(-x)

In [15]:
w = [1,2,3,4]

In [16]:
gradient(w,x_aug,y)

array([-29.08039234, -34.23507179,  15.82110124,  13.94693778])

## Plain Gradient Descent

In [17]:
w = [1,2,3,4]
lr = 0.02
max_iter = 10000

In [18]:
# we need an iteration to update the weights:
for i in range(max_iter):
  w = w -lr*gradient(w,x_aug,y)

In [19]:
w

array([18.55596783,  3.51260743, 14.46970905, -0.07947905])

In [20]:
MSE(w,x_aug,y)

np.float64(2.7841263275531545)

In [25]:
# you can also check the progress in updating the weights
# we need an iteration to update the weights:
w = [1,2,3,4]
for i in range(max_iter):
  w_new = w -lr*gradient(w,x_aug,y)
  if np.mean(abs(w_new-w))<1e-6:
    break
  w = w_new

In [26]:
w

array([18.55517774,  3.51263458, 14.46807804, -0.07908538])

In [27]:
MSE(w,x_aug,y)

np.float64(2.7841264823084977)

## Mini-Batch Stochastic Gradient Descent

In [28]:
w = [1,2,3,4]
lr = 0.02
epochs = 10000
batch_size = 15

In [29]:
# the main idea is two nested for-loops
for i in range(epochs):
  for batch_ind in np.array_split(np.random.permutation(range(len(x))),batch_size):
    xs = x_aug[batch_ind]
    ys = y[batch_ind]
    w_new = w -lr*gradient(w,xs,ys)
    if np.mean(abs(w_new-w))<1e-6:
      break
    w = w_new

In [30]:
MSE(w,x_aug,y)

np.float64(2.786582715188083)

## RMSPROP

RMSprop (Root Mean Square Propagation) is an adaptive learning rate optimization algorithm used to train neural networks more efficiently and stably

In [31]:
w = [1,2,3,4]
eta = 0.02
epsilon = 0.001
gamma =0.9
epochs = 10000
batch_size = 15
s = 0

In [32]:
# the main idea is two nested for-loops
for i in range(epochs):
  for batch_ind in np.array_split(np.random.permutation(range(len(x))),batch_size):
    xs = x_aug[batch_ind]
    ys = y[batch_ind]
    g = gradient(w,xs,ys)
    lr = eta/np.sqrt(s+epsilon)
    w_new = w -lr*g
    s = gamma*s+(1-gamma)*sum(g**2)
    if np.mean(abs(w_new-w))<1e-6:
      break
    w = w_new

In [33]:
MSE(w,x_aug,y)

np.float64(2.784499378628448)